
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "1"
        argocd.argoproj.io/health-check: "true"
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: nginx:1.21
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  key: version
                  name: app-config
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: app-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

