# .github/workflows/cicd.yml
name: Flask CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest src/tests/test.py -v --tb=short

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          eltonaloys/flask-ci-cd-app:latest
          eltonaloys/flask-ci-cd-app:${{ github.sha }}
    
    - name: Test Docker image
      run: |
        docker run -d --name test-app -p 3000:3000 \
          -e ENV=production -e VERSION=1.0.0 \
          eltonaloys/flask-ci-cd-app:latest
        
        sleep 10
        
        # Test endpoints
        curl -f http://localhost:3000/health
        curl -f http://localhost:3000/
        curl -f http://localhost:3000/api/data
        
        docker stop test-app
        docker rm test-app