

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/3lton007/GitOps-Workflow-using-ArgoCD-on-Kubernetes.git"
    targetRevision: main
    path: applications/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true