#prometheus.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-argocd-config
  namespace: argocd
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s

    scrape_configs:
    - job_name: 'argocd-metrics'
      static_configs:
      - targets: ['argocd-metrics:8082']
      scrape_interval: 15s
      metrics_path: /metrics

    - job_name: 'argocd-server-metrics'
      static_configs:
      - targets: ['argocd-server-metrics:8083']
      scrape_interval: 15s
      metrics_path: /metrics

    - job_name: 'argocd-repo-server-metrics'
      static_configs:
      - targets: ['argocd-repo-server:8084']
      scrape_interval: 15s
      metrics_path: /metrics

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-argocd
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-argocd
  template:
    metadata:
      labels:
        app: prometheus-argocd
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.40.0
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-storage
          mountPath: /prometheus
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.enable-lifecycle'
        - '--storage.tsdb.retention.time=7d'
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-argocd-config
      - name: prometheus-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-argocd
  namespace: argocd
spec:
  selector:
    app: prometheus-argocd
  ports:
  - port: 9090
    targetPort: 9090
