


apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: ClusterIP