
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/demo-app

namespace: dev

commonLabels:
  enviroment: dev

images:
  - name: nginx
    newTag: latest

#dev-specific configuration
configMapGenerator:
  - name: app-config
    behavior: replace
    literals:
      - version=v1.0.0-dev
      - enviroment=development
      - debug=true

#Single replica for dev
patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
